//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bed
    {
        public int ID { get; set; }
        public string Number { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<byte> Available { get; set; }
        public Nullable<int> RoomID { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
