//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public int ID { get; set; }
        public string Fullname { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public Nullable<int> BedID { get; set; }
        public string ISBN { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
    
        public virtual Bed1 Bed { get; set; }
    }
}
